# Generated by Django 5.1.2 on 2024-10-21 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_blogmodel_data_remove_blogmodel_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatorprofilemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloggersProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewersprofilemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewersProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
