# Generated by Django 5.1.2 on 2024-10-21 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='Media/Blog_Pic')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Content', models.CharField(max_length=100, null=True)),
                ('Author', models.CharField(max_length=100, null=True)),
                ('Data', models.CharField(max_length=100, null=True)),
                ('Published', models.CharField(max_length=100, null=True)),
                ('Categories', models.CharField(choices=[('politics', 'Politics'), ('sports', 'Sports'), ('intertainment', 'Intertainment')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloggersProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
